### ISSUE TITLE
Add an optional report

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-tester#2]
April 5 2018:

Brainstorming ideas for a report:

* Date
* Commit hash (if available)
* Repository (if available)
* Syntax check
* Execution time
* First run result
* Idempotence time
* Idempotence result

* Possibility of including a report type with bools and a print function for the type.

**Comment by fubarhouse** [comment]
Here's a brief preview, some of the values do however need to change to be accurate.

The repository information, configuration and docker details are all accurate.

There's currently no scope for inclusion outside the `full` command.

Feedback is welcome for anybody who wishes to contribute - ideas, feedback or criticism is welcome as long as the intention is positive.

```
----------------------------------------------------------
Ansible Role Tester Report
----------------------------------------------------------
Timestamp:                      2018-09-10 20:58:30.993981413 +1000 AEST m=+0.035420784
Repository URL:                 https://github.com/issmirnov/ansible-role-compile-zsh.git
Repository commit:              a73175b2faca9e1c546420feaaae6075b3ddf889
Local changes:                  true
----------------------------------------------------------
Configuration:                  {"Meta":{"Timestamp":"2018-09-10T20:58:30.993981413+10:00","Repository":"https://github.com/issmirnov/ansible-role-compile-zsh.git","CommitHash":"a73175b2faca9e1c546420feaaae6075b3ddf889","LocalChanges":true},"Ansible":{"Config":{"HostPath":"/Users/karl/Projects/Ansible/ansible-role-compile-zsh","Inventory":"","RemotePath":"/etc/ansible/roles/role_under_test","ExtraRolesPath":"","RequirementsFile":"","PlaybookFile":"/tests/playbook.yml","Remote":false,"Verbose":false,"Quiet":false},"Syntax":true,"Requirements":false,"Run":{"Result":true,"Time":0},"Idempotence":{"Result":true,"Time":0}},"Docker":{"Run":true,"Kill":true}}
Syntax check:                   true
Requirements installed:         false
Run result:                     true
Run time:                       0s
Idempotence result:             true
Idempotence time:               0s
----------------------------------------------------------
Docker run:                     true
Docker kill:                    true
----------------------------------------------------------
```

**Comment by fubarhouse** [comment]
If there's no feedback directly to this issue, this change will proceed in the next couple of days. A PR is about to be opened.

**Comment by issmirnov** [comment]
Looks awesome! Would it be possible to have a flag to output the report as a raw json? This would be useful to feed into `jq` or some central database. Since the data is already in a marshalled struct (at `report.Printf()`), hopefully it wouldn't be too complicated.

**Comment by fubarhouse** [comment]
@issmirnov,

That sounds achievable, could you elaborate a little more?

For example, "A new flag which only outputs a json version of the whole report", or "A new flag which adds a marshalled json of that report to the report".

Something which will describe exactly what your idea is, even if it is one of those examples.

This example may need some extra work, for example starting and removing containers still has output, but it's a step towards that.

**Comment by fubarhouse** [comment]
Implicit, but could you provide some more input to the above solution in branch issue-2?

**Comment by issmirnov** [comment]
Oh wow, this looks fantastic!!

> output yml/json versions outputted to file instead of stdout

I have a mild preference for stdout, since then one can pipe into [jq](https://stedolan.github.io/jq/tutorial/) or [httpie](https://httpie.org/). It's not hard to add a redirect to a file if needed - stdout seems more flexible. What do you think?

A couple of notes:
- The YAML output is beautiful, +1 to having this in github issues templates.
- Agreed that this only makes sense in the `full` command.
- Looking at 04e54ec, I'm not sure what you're doing with `identifiedError`. The general convention is to do a standard `if err != nil {return err}` check, and for subsequent errors simply redefine err (so `=` rather than `:=`). You can see a sample [here](https://github.com/issmirnov/zap/blob/a819ed1dda083f9fb04bc951893655bfe02a09b8/main.go#L38)

**Comment by fubarhouse** [comment]
@issmirnov, in response to your third note I agree...

I'll do some testing tonight to see how that impacts the end result. Worst case scenario I suppose it simply won't be written to a file.

As for stdout... 

The container start and kill is still in stdout, as well as all other fields. Are you able to __provide a full example of what the stdout would look like__, or would it simply be as previously provided, simply a field in the output.

My worry is the only output of the command being the json, because there's log messages and docker responses which would hinder manual parsing. using `awk`, `grep` and `cut` isn't exactly an elegant solution and believe me I've been down that road.

**Comment by issmirnov** [comment]
@fubarhouse 

You are **completely correct**. I had forgotten that the stdout contains the docker and ansible output. Serves me right for commenting on Github after a long day at work!

Absolutely, a file makes much more sense. I see you've added logic to write the appropriate format depending on the output file extension. Looks great to me.

**Comment by fubarhouse** [comment]
I'll get the errors sorted tonight, hopefully we can merge tomorrow!

**Comment by fubarhouse** [comment]
@issmirnov,

The changes are once again ready for review if you wish to provide feedback.

**Comment by issmirnov** [comment]
Looks great! Added some comments about some style suggestions to conform with more idiomatic go. The cascading error pattern can be hard to discover since one has to use named returns.

- [Named Returns](https://tour.golang.org/basics/7)
- [Chained errors](https://play.golang.org/p/X_iQWgjuO0o)

**Comment by fubarhouse** [comment]
@issmirnov,

Here's a patch - much less elegant than creating a commit.

Could you review it to see if it's like what you're getting at?

````
diff --git a/util/report.go b/util/report.go
index 998a8f6..c4e36b7 100644
--- a/util/report.go
+++ b/util/report.go
@@ -190,7 +190,7 @@ func (report *AnsibleReport) GetYAML(data interface{}) ([]byte, error) {
 
 // printFile will output the input data to the given filename.
 // Intended for exclusive use by GetJSON and GetYAML.
-func (report *AnsibleReport) printFile(data []byte) error {
+func (report *AnsibleReport) printFile(data []byte) (err error) {
 
 	filename := report.Meta.ReportFile
 
@@ -200,22 +200,22 @@ func (report *AnsibleReport) printFile(data []byte) error {
 		if err = os.Remove(filename); err != nil {
 			// The file could not be deleted
 			log.Errorf("failed to delete %v\n", filename)
-			return err
+			return
 		}
 	}
 
 	// Assume no file is available.
 	if _, err := os.Stat(filename); err != nil {
-		if file, fe := os.Create(filename); fe != nil {
+		if file, err := os.Create(filename); err != nil {
 			// File could not be created.
 			log.Errorf("could not create file %v\n", filename)
-			return fe
+			return
 		} else {
 			// File was created, attempt to write to it
-			if we := ioutil.WriteFile(filename, data, 0644); we != nil {
+			if err := ioutil.WriteFile(filename, data, 0644); err != nil {
 				// Could not write to file.
 				log.Errorf("could not write data to %v\n", filename)
-				return we
+				return
 			} else {
 				// Wrote to file successfully.
 				log.Infof("Report data has been written to %v\n", filename)
@@ -225,7 +225,7 @@ func (report *AnsibleReport) printFile(data []byte) error {
 			defer file.Close()
 		}
 	}
-	return nil
+	return
 
 }
 
````

**Comment by issmirnov** [comment]
@fubarhouse 

Close, but you'll want to keep the `return` statements inside the error handlers, otherwise the execution won't break out at the appropriate point. So with named returns, the only thing that changes is that you don't have to manually specify *what* to return, but you still need the `return` statements.

**Comment by fubarhouse** [comment]
I did run into return shadowing issues when using multiple returns and named returns... I'll give it another go.

**Comment by issmirnov** [comment]
@fubarhouse 

I'm honored to provide feedback, thank you for being open to it!

A few comments:
- I really like how the various util functions return `(success bool [, time.Duration])` now - makes a ton of sense and easier flow control. 
- The report logic seems very reasonable, I'm sure it will continue to be useful in the future, especially for debugging.
- I did notice that running a diff against `master` showed that this PR will undo some of the changes in #47 and may completely undo #53 - flagging for you so that you can take care when setting up the merge. You'll probably want to try `git rebase master -i` and follow it with a `gofmt -s -w .`. Depending on your preferences on the git history flow, you may be interested in [squashing](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) all of the commits on this PR into 1-2 logical units (`git rebase master -i` and mark commits with `s` for squash). Since it's a feature branch one could argue that force pushing is completely allowed.

**Comment by fubarhouse** [comment]
Merged!
