### ISSUE TITLE
Bug in idempotence time reporting

### ISSUE THREAD

**Issue by issmirnov** [fubarhouse/ansible-role-tester#55]
Hi,

I noticed that my runs are showing:
```
INFO[0166] Idempotence was checked in 433ns
```

Looks like there's a bug at https://github.com/fubarhouse/ansible-role-tester/blob/master/util/idempotence.go#L62 - this will print the time delta of those two statements, rather than the delta to the start time of the idempotence run.

This is due to my mistake in #41. I'll send a fix soon.

**Comment by issmirnov** [comment]
Sent a fix in #56 . It's interesting to note that the reports in #2 were showing the correct time.

**Comment by fubarhouse** [comment]
Cool.

Yeah, I was aware of it though I hadn't submitted an issue.

There's opportunity here to expand on the reporting mechanism to the run, install and kill commands to add to the report - and allow the tool to use the values directly instead of generating new ones.

I'll get this merged shortly - that can always be explored later.
